### PR TITLE
Layout cleanup

### PR DESCRIPTION
**Pull request by alkamin**
## Overview

This PR does a few things in service of cleanup and consistency:
1) Cleans up the `Header` component. b407625 and d6ca52d
2) Moves the overall layout to flex-box all the way down 249510b

### Header changes
1) Moves to a directory based approach for the component
2) Creates `styles.ts` to handle the quantity of `mergeStyles` generated classes
3) Moves `HeaderLink` into `src/components/Header/components` to co-locate the components that are only used within the Header component (this is a pretty opinionated move and the component could stay in `src/components` or even next to the index file as `src/components/Header/HeaderLink.tsx`)
4) Removes all inline styles and implements the _mostly_ same files using `mergeStyles` to generate dynamic CSS classes.
5) Makes a slight adjustment to yml import to please the TypeScript compiler
6) Converts any touched files to TS
7) Adjusts styles so when wrapping occurs, all header content is aligned to the same left axis

### Layout changes
The goal of these changes was to remove the need to have short and long layout variations along with the hardcoding or detection of header and footer sizes. For pages that might be shorter than the window height, the footer remains at the bottom of the window. When those pages grow, the footer appears at the bottom of the content as expected. For Fixed height layouts (such as the Explorer), we lean on flex-box to allow the content to grow to fill the screen. To summarize, this commit:

1) removes all `isShort` usage
2) removes all hardcoded sizes
3) adjusts the structure of the DOM and top-level CSS to allow for flex-box element stacking

## Testing
1) Ensure the header looks correct under various screen size scenarios
2) Ensure that the all other pages look correct in their overall layout, especially the Explorer.

### CODE REVIEW

**Comment by alkamin** [comment]
@mmcfarland I don't think I can assign. But this is ready for review.

**Comment by mmcfarland** [comment]
Thanks, @alkamin this looks great. In testing, I found one issue with the new layout, and it's a bit tricky. If you look at the Explorer on this branch, the sidebar results panel does not get a fixed height equal to the screen height when the number of results exceeds the height. Rather than scroll the overflow, it just pushes the bottom of the page all the way down. You should be able to recreate it with this localhost url:
http://localhost:3000/explore?c=-6.1494%2C38.8686&z=6.07&r=Elevation+%28terrain%29&d=cop-dem-glo-90&m=Most+recent

and compare it to the existing behavior here:
https://planetarycomputer-staging.microsoft.com/explore?c=-6.1494%2C38.8686&z=6.07&r=Elevation+%28terrain%29&d=cop-dem-glo-90&m=Most+recent

I say it's tricky, because @jfrankl and I had some trouble initially getting that behavior to work. What ended up being key was setting a (calculated) fixed height on the `main` element, plus some height and overflow settings on various children. The working solution basically came down to this commit https://github.com/microsoft/PlanetaryComputerDataCatalog/commit/b90ac0e119e5402ff4a8c61e28ef475c64d16054

It would be ideal if we didn't have to use any calculated heights, but in the absence of an alternative, it might be expedient to continue to use it in this case. Can you take a look at adapting this PR to allow for a scrollable side panel there?

**Comment by mmcfarland** [comment]
@alkamin Also, I'm not sure why PRs from forks aren't using the ephemeral staging deployments, I'll look into getting that enabled so the changes can be reviewed and tested more easily.

**Comment by alkamin** [comment]
I don't want this PR to linger with the abnormal schedule around this time of year so I am going to revert the layout commit and attempt to get the scrolling working within a separate PR.

**Review by mmcfarland — APPROVED** [review]
Looks good, thanks for the cleanup. 

General question, do you have a rule of thumb on when to use component specific `IStyle` objects applied as props (usually as a const) vs the `mergeStyle` className approach. I've gravitated towards the `I{name}Style` approach mostly because they can be typed and target various subcomponents in the higher level component, and haven't used `mergeStyles` very much.

**Comment by alkamin** [comment]
Good question. If you like the multi-level functionality then `mergeStyleSets` should provide something pretty close to that (though I find the usage a bit less clear than just using `mergeStyles`). I tried to stick with the guidelines outlined here: https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/README.md and didn't end up experimenting too much with the styles object approach.

The types seem for both seem to lean on `IStyle` so I wouldn't expect any differences in that realm. `IStyle` is pretty permissive (it's a union of [`IRawStyle`](https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/src/IRawStyle.ts#L11-L31) style among other things and hasn't helped me avoid typos.

**Pull request merged**
