### PR TITLE
Datasets.yml updates

### PR DESCRIPTION
**Pull request by pholleway**
datasets.yml file updates 

- added drcog
- updated viirs-10a1-001 category from water/snow to snow
- added viirs notebook links
- added chesapeake notebook links

- added notebook links to [etl/config/codefiles_urls.txt](https://github.com/microsoft/PlanetaryComputerDataCatalog/pull/342/files#diff-fa9afef391c95c39b04d026cce4c485edcec924d3cd94c166a562cb0453460f8)

### CODE REVIEW

**Comment by pholleway** [comment]
cc @pjhartzell

**Comment by pholleway** [comment]
Adding viirs notebook links before requesting review

**Comment by pholleway** [comment]
@mmcfarland This PR is ready for review. I don't have the permissions to add you as a reviewer. Thanks!

**Review by mmcfarland — COMMENTED** [review]
Looks good. One thing: for every new ipynb referenced, we'll need to add a line in this codefiles_urls.txt file which downloads them as a separate step.

https://github.com/microsoft/PlanetaryComputerDataCatalog/blob/develop/etl/config/codefiles_urls.txt#L48

**Comment by mmcfarland** [comment]
> Is it okay to add the links before the notebooks are done?

Yep, the build will just move on without them. The tab will start working once the notebooks exist and this site gets redeployed.

**Pull request merged**
