### PR TITLE
Added gpm-imerg-hhr

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by mmcfarland** [comment]
Yeah - this is catching some kind of actual bug, I think in the tiler service or maybe the frontend (but not this branch). I'm looking into it now.

**Comment by mmcfarland** [comment]
@TomAugspurger  I think you maybe branched off of `main` instead of `develop` to add this PR so it's missing some commits related to the new titiler url params, which are causing preview images not to load, and the tests to fail.

**Comment by TomAugspurger** [comment]
🤦yeah, I did, sorry. I'll rebase and force-push.

**Comment by TomAugspurger** [comment]
The missing image due to a typo in the `thumbnail` in the collection. I've fixed that upstream and will re-ingest the collection.

**Pull request merged**
